test_that("enrichment requires explicit engines and preserves universe losses", {
  d <- association_fixture(K=8)
  pathways <- list(one=c("g1","g2","g3"),empty="unknown")
  expect_error(enrich_factors(d$view,pathways),"explicitly")
  empty <- enrich_factors(d$view,list(none="unknown"),"fgsea")
  expect_equal(nrow(empty$table),0L)
  expect_equal(empty$analysis_metadata$status,"no_overlapping_pathways")
  expect_error(enrich_factors(d$view,pathways,"susie"),"unsupported")
  expect_error(enrich_factors(d$view,pathways,"fgsea",feature_map=c(g1="x",g2="x")),"unique")
  expect_error(.check_engine("flashbridge_missing_engine"),"install it explicitly")
})

test_that("ranked fgsea results agree directly with the selected engine", {
  skip_if_not_installed("fgsea")
  d <- association_fixture(K=8)
  pathways <- list(one=c("g1","g2","g3"),two=c("g4","g5","g6"))
  # Distinct effects avoid native ties in this parity fixture.
  d$view$effects <- matrix(seq_len(64),8,dimnames=list(paste0("g",1:8),paste0("F",1:8)))
  d$view <- .make_representation(d$view$activity,d$view$effects,d$view$manifest)
  settings <- list(seed=4,nPermSimple=100L,eps=1e-3,minSize=2L,scoreType="pos")
  out <- enrich_factors(d$view,pathways,"fgsea",factors="F1",control=settings)
  set.seed(4)
  native <- as.data.frame(fgsea::fgseaMultilevel(pathways,setNames(d$view$effects[,1],rownames(d$view$effects)),BPPARAM=BiocParallel::SerialParam(),nPermSimple=100L,eps=1e-3,minSize=2L,scoreType="pos"))
  expect_equal(out$table$NES,native$NES)
  expect_equal(out$table$pval,native$pval)
  expect_equal(out$analysis_metadata$universe,rownames(d$view$effects))
})

test_that("decoupleR returns native method-specific scores", {
  skip_if_not_installed("decoupleR")
  d <- association_fixture(K=8)
  d$view$effects <- matrix(seq_len(64),8,dimnames=list(paste0("g",1:8),paste0("F",1:8)))
  d$view <- .make_representation(d$view$activity,d$view$effects,d$view$manifest)
  sets <- list(one=c("g1","g2","g3"),two=c("g4","g5","g6"))
  out <- enrich_factors(d$view,sets,"decoupleR",control=list(method="ulm",minsize=2L))
  network <- data.frame(source=rep(names(sets),each=3),target=unlist(sets),mor=1)
  native <- as.data.frame(decoupleR::run_ulm(d$view$effects,network,minsize=2L))
  expect_equal(out$table$score,native$score)
  expect_equal(out$analysis_metadata$interpretation,"network_activity_score")
  mlm <- enrich_factors(d$view,sets,"decoupleR",control=list(method="mlm",minsize=2L))
  direct <- as.data.frame(decoupleR::run_mlm(d$view$effects,network,minsize=2L))
  expect_equal(mlm$table$score,direct$score)
  expect_equal(mlm$table$p_value,direct$p_value)
})
