test_that("Seurat reductions align cells and loadings without overwriting", {
  skip_if_not_installed("SeuratObject")
  d<-association_fixture()
  counts<-matrix(1,4,12,dimnames=list(rownames(d$view$effects),rev(rownames(d$view$activity))))
  object<-SeuratObject::CreateSeuratObject(Matrix::Matrix(counts,sparse=TRUE),min.cells=0,min.features=0)
  result<-add_factors_to_seurat(object,d$view)
  A<-SeuratObject::Embeddings(result[["ebmf"]])
  expect_equal(unname(A),unname(d$view$activity[colnames(object),]))
  expect_equal(unname(SeuratObject::Loadings(result[["ebmf"]])),unname(d$view$effects))
  expect_equal(SeuratObject::Misc(result[["ebmf"]],"flashier.utils")$basis_id,d$view$manifest$basis_id)
  expect_error(add_factors_to_seurat(result,d$view),"already exists")
  expect_error(add_factors_to_seurat(object,d$view,reduction="bad_key"),"alphanumeric")
  alien<-SeuratObject::CreateSeuratObject(Matrix::Matrix(matrix(1,4,3,dimnames=list(paste0("x",1:4),paste0("c",1:3))),sparse=TRUE))
  expect_error(add_factors_to_seurat(alien,d$view),"Cell IDs")
  incompatible<-SeuratObject::CreateSeuratObject(Matrix::Matrix(matrix(1,3,12,dimnames=list(paste0("x",1:3),colnames(object))),sparse=TRUE))
  out<-add_factors_to_seurat(incompatible,d$view)
  expect_equal(nrow(SeuratObject::Loadings(out[["ebmf"]])),0L)
  expect_equal(d$view$activity,association_fixture()$view$activity)
})
