test_that("descriptive summaries match IDs, units, weights and first-minus-second", {
  view <- fixture_view()
  md <- data.frame(sample=c("s3","s1","s2"),group=c("B","A","A"),donor=c("d2","d1","d1"),age=c(5,1,2))
  out <- summarize_factor_activity(view,md,"group",unit_col="donor")
  expect_equal(out$mean[out$group=="A"],c(1.5,1))
  expect_equal(out$n_units[out$group=="A"],c(1L,1L))
  weighted <- summarize_factor_activity(view,md,"group",weights=c(s1=1,s2=3,s3=1))
  expect_equal(weighted$mean[weighted$group=="A"],c(1.75,0.5))
  expect_true(all(is.na(weighted$q25)))
  contrast <- compare_factor_groups(view,md,"group",c("A","B"),unit_col="donor")
  expect_equal(contrast$factor_contrast$estimate,c(-2.5,2))
  expect_equal(contrast$feature_contrast$estimate,c(1, -1.5, 8, -2.5))
  expect_false("p.value" %in% names(contrast$factor_contrast))
  reverse <- compare_factor_groups(view,md,"group",c("B","A"))
  expect_equal(reverse$feature_contrast$estimate,-contrast$feature_contrast$estimate)
  rank <- rank_factors_by_metadata(view,md,"age")
  native <- lm(view$activity[,1] ~ md$age[match(rownames(view$activity),md$sample)])
  expect_equal(rank$value[1],summary(native)$r.squared)
})
