test_that("audited helpers agree on signed effects and tied ranks", {
  B <- rbind(c(4,0,0),c(1,-1,0),c(4,0,3),c(2,0,-4),c(0,-4,0),c(0,-4,-3),c(0,-2,-4),c(1,-2,4),c(0,0,0))
  dimnames(B) <- list(paste0("g",1:9),paste0("F",1:3))
  expect_equal(.rank_effects(B),upstream_rank_effects(B))
  expect_equal(.compute_le_effects(B),upstream_compute_le_effects(B))
  expect_equal(.compute_le_effects(B)[1,],c(F1=4,F2=0,F3=0))
  expect_equal(.compute_le_effects(B)[6,],c(F1=0,F2=-1,F3=0))
  expect_equal(.compute_le_effects(B[,1,drop=FALSE]),B[,1,drop=FALSE])
  expect_equal(.compute_le_effects(B[6,,drop=FALSE]),upstream_compute_le_effects(rbind(B[6,],B[6,]))[1,,drop=FALSE],ignore_attr=TRUE)
  view <- fixture_view()
  rows <- factor_features(view,"F1",select="both",n=2)
  expect_setequal(rows$selection,c("largest","distinctive"))
  expect_true(all(factor_features(view,"F1",select="largest",direction="negative")$estimate < 0))
  expect_equal(nrow(factor_features(view,"F1",n=0)),0)
})
