test_that("lm contrasts, SE and joint covariance match native engines", {
  d <- association_fixture()
  out <- test_factors(d$view,d$metadata,~group,"lm",unit_col="donor",independence="independent",control=list(joint_coefficient_covariance=TRUE))
  native <- lm(d$view$activity[,1] ~ group,data=d$metadata)
  expect_equal(out$table$estimate[1],unname(coef(native)["groupB"]))
  expect_equal(out$table$std.error[1],unname(summary(native)$coefficients["groupB","Std. Error"]))
  expect_equal(out$table$adj.p.value,p.adjust(out$table$p.value,"BH"))
  joint <- lm(d$view$activity ~ group,data=d$metadata)
  V <- vcov(joint); index <- match(paste0(colnames(d$view$activity),":groupB"),rownames(V))
  expect_equal(unname(out$coefficient_covariance$groupB),unname(V[index,index]))
  reverse <- matrix(c(0,-1),2,dimnames=list(c("(Intercept)","groupB"),"AminusB"))
  reversed <- test_factors(d$view,d$metadata,~group,"lm",unit_col="donor",independence="independent",contrasts=reverse)
  expect_equal(reversed$table$estimate,-out$table$estimate)
  expect_equal(attr(out$table,"analysis_metadata")$basis_id,d$view$manifest$basis_id)
})
