test_that("native activity transfer preserves programs in both orientations", {
  v <- fixture_view(); Y <- tcrossprod(v$activity,v$effects)
  priors <- list(ebnm::ebnm_normal,ebnm::ebnm_point_laplace)
  for(side in c("rows","columns")) {
    p <- if(side=="rows") priors else rev(priors)
    query <- if(side=="rows") Y[3:1,4:1] else t(Y[3:1,4:1])
    r <- project_factor_activity(v,query,side,"arcsinh_intensity",list(scope="identity"),ebnm_fn=p,maxiter=5)
    expect_identical(r$representation$effects,v$effects)
    expect_identical(r$representation$offset,v$offset)
    expect_equal(rownames(r$representation$activity),c("s3","s2","s1"))
    expected <- .native_projection(Y[3:1,,drop=FALSE],v,side,p,maxiter=5)
    expect_equal(r$representation$activity,expected)
    expect_equal(r$analysis_metadata$source_basis_id,v$manifest$basis_id)
    reference <- .prediction_metrics(Y[3:1,],tcrossprod(expected,v$effects)); names(reference)[names(reference)=="prediction_r2"] <- "fit_r2"
    expect_equal(r$reconstruction,reference)
  }
  sparse <- Matrix::Matrix(Y,sparse=TRUE)
  r <- project_factor_activity(v,sparse,"rows","arcsinh_intensity",list(scope="identity"),ebnm_fn=priors,maxiter=5)
  expect_identical(r$representation$effects,v$effects)
})
test_that("new feature projection agrees with explicit native calls", {
  v <- fixture_view(); A <- v$activity
  M <- cbind(P1=c(s1=1,s2=2,s3=5),P2=c(3,0,-2)); priors <- list(ebnm::ebnm_normal,ebnm::ebnm_point_laplace)
  for(side in c("rows","columns")) {
    p <- if(side=="rows") priors else rev(priors)
    Y <- M[3:1,,drop=FALSE]; a <- A[3:1,]
    r <- project_factor_features(v,if(side=="rows") Y else t(Y),side,"protein",ebnm_fn=p,maxiter=5)
    expect_identical(r$representation$activity,a)
    b <- t(qr.coef(qr(a),Y))
    native <- flashier::flash_init(if(side=="rows") Y else t(Y),var_type=if(side=="rows") 2 else 1)
    native <- flashier::flash_factors_init(native,if(side=="rows") list(a,b) else list(b,a),ebnm_fn=p)
    native <- flashier::flash_factors_fix(native,1:2,which_dim=if(side=="rows") "loadings" else "factors")
    native <- flashier::flash_backfit(native,maxiter=5,extrapolate=FALSE,verbose=0)
    expect_equal(unname(r$representation$effects),unname(if(side=="rows") native$F_pm else native$L_pm))
  }
})
test_that("transfer rejects integrity, units, rank and budget failures", {
  v <- fixture_view(); Y <- tcrossprod(v$activity,v$effects); priors <- list(ebnm::ebnm_normal,ebnm::ebnm_point_laplace)
  run <- function(q=Y,...) project_factor_activity(v,q,"rows","arcsinh_intensity",list(scope="identity"),ebnm_fn=priors,...)
  expect_error(run(Y[,1:2]),"Exact")
  expect_error(run(Y[,1,drop=FALSE],feature_match="intersection"),"Insufficient")
  r <- run(Y[,1:3],feature_match="intersection",maxiter=5)
  expect_identical(r$representation$effects,v$effects); expect_equal(r$analysis_metadata$coverage,0.75)
  expect_error(run(dense_budget_bytes=1),"allocations")
  expect_error(project_factor_activity(v,Y,"rows","logcounts",list(scope="identity"),ebnm_fn=priors),"incompatible")
  expect_error(project_factor_activity(v,Y,"rows","arcsinh_intensity",NULL,ebnm_fn=priors),"manifest")
  expect_error(project_factor_activity(v,Y,"rows","arcsinh_intensity",list(scope="identity")),"explicit ebnm_fn")
  expect_error(run(Matrix::Matrix(Y,sparse=TRUE),S=1),"Sparse")
  dup <- Y; rownames(dup)[1] <- rownames(dup)[2]; expect_error(run(dup),"unique")
  expect_error(project_factor_features(v,Y[1,,drop=FALSE],"rows","protein",ebnm_fn=priors),"Rank-deficient")
  bad <- Y; rownames(bad)[1] <- "absent"
  expect_error(project_factor_features(v,bad,"rows","protein",ebnm_fn=priors),"absent")
  mapped <- Y; colnames(mapped) <- paste0("q",1:4)
  m <- setNames(rownames(v$effects),colnames(mapped))
  expect_equal(run(mapped,gene_mapping=m,maxiter=5)$representation$effects,v$effects)
  m[2] <- m[1]; expect_error(run(mapped,gene_mapping=m),"unique")
})
test_that("inferred priors, subsets, nonzero offsets and S retain declared coordinates", {
  f <- fixture_fit(); v <- standardize_factors(f,scaling="raw")
  Y <- fixture_matrix()
  # fixture_fit deliberately leaves units unknown: declarations fail closed.
  expect_error(project_factor_activity(v,Y,"rows","unknown",list(scope="identity")),"non-unknown")
  v <- .make_representation(v$activity,v$effects,utils::modifyList(v$manifest,list(feature_scale="simulated")))
  inferred <- suppressWarnings(project_factor_activity(v,t(Y),"columns","simulated",list(scope="identity"),maxiter=3))
  expect_identical(inferred$representation$effects,v$effects)
  new <- suppressWarnings(project_factor_features(v,Y[12:1,1:3],"rows","protein",maxiter=3))
  expect_identical(new$representation$activity,v$activity[12:1,,drop=FALSE])
  offset <- setNames(rep(1,nrow(v$effects)),rownames(v$effects))
  shifted <- .make_representation(v$activity,v$effects,v$manifest,offset=offset)
  query <- sweep(Y,2,offset,"+")
  sparse <- Matrix::Matrix(query,sparse=TRUE)
  r <- suppressWarnings(project_factor_activity(shifted,sparse,"rows","simulated",list(scope="identity"),maxiter=3))
  expect_identical(r$representation$offset,offset)
  expect_identical(r$representation$effects,v$effects)
  expect_true(is.logical(r$native_iteration_diagnostics$iteration_limit_reached))
  expect_equal(r$native_iteration_diagnostics$iteration_limit,3)
  expect_error(project_factor_activity(shifted,sparse,"rows","simulated",list(scope="identity"),dense_budget_bytes=400),"allocations")
  selected <- suppressWarnings(project_factor_activity(v,Y,"rows","simulated",list(scope="identity"),factors=rev(colnames(v$effects)),maxiter=3))
  expect_equal(colnames(selected$representation$effects),colnames(v$effects))
  S <- matrix(1,nrow(Y),ncol(Y),dimnames=dimnames(Y))
  a <- suppressWarnings(project_factor_activity(v,Y[12:1,8:1],"rows","simulated",list(scope="identity"),S=S,maxiter=3))
  b <- suppressWarnings(project_factor_activity(v,Y[12:1,8:1],"rows","simulated",list(scope="identity"),S=S[12:1,8:1],maxiter=3))
  expect_equal(a$representation$activity,b$representation$activity)
  bad <- v$effects; bad[,2] <- 0
  zero <- .make_representation(v$activity,bad,v$manifest)
  expect_error(project_factor_activity(zero,Y,"rows","simulated",list(scope="identity")),"rank-deficient")
})
