test_that("signed displays retain estimates and bound long expansion", {
  view <- fixture_view()
  p <- plot_factor_features(view,c("F1","F2"),n=4)
  expect_s3_class(p,"ggplot")
  expect_true(any(p$data$estimate < 0))
  metadata <- data.frame(sample=c("s3","s1","s2"),cohort=c("b","a","a"))
  p <- plot_factor_activity(view,metadata,group="cohort",max_samples=2L,seed=3)
  expect_equal(length(unique(p$data$sample)),2)
  expect_equal(nrow(p$data),4)
  expect_setequal(p$data$group,c("a","b"))
  expect_error(plot_factor_activity(view,style="structure",display_normalization="row_sum"),"non-negative")
  expect_error(plot_factor_activity(view,style="structure"),"explicit")
  positive <- .make_representation(abs(view$activity),view$effects,view$manifest)
  p <- plot_factor_activity(positive,style="structure",display_normalization="row_sum")
  expect_equal(as.numeric(tapply(p$data$estimate,p$data$sample,sum)),c(1,1,1))
  expect_equal(positive$activity,abs(view$activity))
  positive$activity[1,] <- 0
  positive <- .make_representation(positive$activity,positive$effects,positive$manifest)
  p <- plot_factor_activity(positive,style="structure",display_normalization="row_sum",palette=c(F1="blue",F2="red"),limits=c(0,1))
  expect_equal(attr(p,"analysis_metadata")$zero_activity_samples,"s1")
})
