test_that("signed network selection and comparison pools are hand calculable", {
  view <- fixture_view(); saved <- view
  network <- factor_network(view,direction="both",n=1)
  expect_equal(network$edges$feature,c("g1","g2","g3","g2"))
  expect_equal(network$edges$weight,c(1,-0.5,1,-0.5))
  expect_true(all(network$edges$from!=network$edges$to))
  expect_equal(factor_distinctiveness(view,format="matrix",compare_factors="F1")[,"F1"],view$effects[,"F1"])
  expect_equal(factor_distinctiveness(view,format="matrix")["g1","F1"],0)
  expect_equal(plot_feature_rankings(view,"F1")$data$difference,c(-1,1,-4,1))
  expect_equal(plot_feature_rankings(view,"F1",direction="negative")$data$difference,c(-1,1,-4,1))
  expect_equal(factor_features(view,"F1",select="distinctive",compare_factors="F1")$feature,c("g1","g2","g4"))
  p <- plot_factor_features(view,c("F1","F2"),features=c("g1","g3"),display_normalization="max_abs",annotation=c(F1="a",F2="b"),transpose=TRUE)
  expect_equal(p$data$estimate,c(1,0,0.75,1))
  expect_error(factor_network(view,threshold=-1),"threshold")
  expect_error(plot_feature_rankings(view,"F1",compare_factors="bad"),"Unknown")
  expect_identical(view,saved)
})
test_that("diagnostic definitions, expression axis and annotation stay explicit", {
  v <- fixture_view(); d <- factor_diagnostics(v)
  expect_equal(d$factors$active_proportion,c(1,1/3))
  expect_equal(d$factors$active_features,c(3,3))
  expect_equal(d$samples$programs,c(2,1,1))
  expect_equal(factor_diagnostics(v,activity_direction="absolute")$samples$programs,c(2,1,2))
  s <- summarize_factors(v,annotations=c(F1="user label",F2="unknown"))
  expect_equal(s$annotation,c("user label","unknown"))
  p <- plot_factor_signature(v,"F1",setNames(1:4,paste0("g",1:4)),"log expression")
  expect_equal(p$data$expression,1:4)
  expect_match(p$labels$y,"Mean expression")
  expect_error(plot_factor_signature(v,"F1",c(g1=1),"unknown"),"every feature|non-unknown")
})
test_that("native pROC direction, constants and absent groups are explicit", {
  skip_if_not_installed("pROC"); v <- fixture_view()
  md <- data.frame(sample=c("s3","s1","s2"),group=c("high","low","low"),unit=c("u2","u1","u1"))
  r <- factor_specificity(v,md,"group",groups=c("high","absent"),unit_col="unit")
  expect_equal(r$auc[r$factor=="F1" & r$group=="high"],1)
  expect_equal(factor_specificity(v,md,"group",groups="high",direction="negative")$auc[1],0)
  expect_true(all(r$status[r$group=="absent"]=="unavailable_absent_class"))
  roc <- pROC::roc(c(FALSE,FALSE,TRUE),v$activity[,1],levels=c(FALSE,TRUE),direction="<",quiet=TRUE)
  best <- pROC::coords(roc,"best",best.method="closest.topleft",transpose=FALSE)
  expect_equal(r$threshold[1],min(best$threshold[is.finite(best$threshold)]))
  v2 <- .make_representation(cbind(F1=c(s1=1,s2=1,s3=1)),v$effects[,"F1",drop=FALSE],utils::modifyList(v$manifest,list(native_indices=1)))
  c <- factor_specificity(v2,md,"group",groups="high")
  expect_equal(c$auc,0.5); expect_true(is.na(c$threshold)); expect_equal(c$status,"constant_predictor")
})
test_that("marker gates use identical populations and deterministic activity ties", {
  v <- fixture_view(); M <- cbind(CD1=c(s3=2,s2=0,s1=3),CD2=c(0,1,0))
  r <- factor_gate_alignment(v,M,"F1",positive="CD1",negative="CD2",thresholds=c(CD1=1,CD2=0.5))
  expect_equal(r$gate_ids,c("s1","s3")); expect_equal(r$activity_ids,c("s3","s2"))
  expect_equal(r$summary$overlap_fraction,0.5); expect_equal(r$summary$n_gate,r$summary$n_activity)
  empty <- factor_gate_alignment(v,M,"F1",positive="CD1",thresholds=c(CD1=5))
  expect_true(is.na(empty$summary$jaccard)); expect_length(empty$activity_ids,0)
  expect_error(factor_gate_alignment(v,M,"F1",positive="missing",thresholds=c(CD1=1)),"Unknown")
  expect_error(factor_gate_alignment(v,M,"F1",positive="CD1",thresholds=c(CD2=1)),"Missing")
  low <- factor_gate_alignment(v,M,"F1",positive="CD1",negative="CD2",thresholds=c(CD1=1,CD2=0.5),direction="low")
  expect_equal(low$gate_ids,r$gate_ids); expect_equal(low$activity_ids,c("s1","s2"))
  expect_equal(low$summary$direction,"low"); expect_equal(attr(low,"analysis_metadata")$tie_rule,"ascending_activity_then_sample_ID")
  expect_equal(r$summary$direction,"high")
  expect_error(factor_gate_alignment(v,M,"F1",positive="CD1",thresholds=c(CD1=1),direction="up"),"arg")
  c <- correlate_factor_markers(v,M)
  expect_equal(c$correlation[1],cor(v$activity[,1],M[rownames(v$activity),1]))
})
test_that("mclust candidates match namespace-only native fits and preserve RNG", {
  skip_if_not_installed("mclust")
  set.seed(13); M <- cbind(CD1=c(rnorm(100,2,0.1),rnorm(100,5,0.1))); rownames(M) <- paste0("s",1:200)
  old <- .Random.seed
  r <- estimate_marker_thresholds(M,thresholds=c(CD1=3))
  expect_identical(.Random.seed,old)
  expect_equal(r$thresholds$threshold,3); expect_equal(r$thresholds$source,"supplied")
  mclustBIC <- mclust::mclustBIC
  native <- .with_seed(42,mclust::Mclust(M[,1],G=2,verbose=FALSE))
  expect_equal(r$thresholds$candidate,max(M[native$classification==which.min(native$parameters$mean),1]))
  expect_equal(r$thresholds$bic_two,native$bic)
  expect_false(r$thresholds$manual_review)
  expect_true(estimate_marker_thresholds(M[1:10,,drop=FALSE])$thresholds$manual_review)
  constant <- M; constant[,1] <- 2
  expect_equal(estimate_marker_thresholds(constant)$thresholds$status,"constant_marker")
})
test_that("unequal-variance mixtures flag nonmonotone candidates for review", {
  skip_if_not_installed("mclust")
  set.seed(1); x <- c(rnorm(400,1.5,1.2),rnorm(200,4,0.25)); M <- cbind(CD1=x); rownames(M) <- paste0("s",seq_along(x))
  t <- estimate_marker_thresholds(M,eligible_above=-100)$thresholds
  expect_true(t$manual_review); expect_match(t$status,"nonmonotone_classification")
  expect_lt(t$candidate,max(x)); expect_identical(rownames(t),"1")
})
test_that("plot rendering retains RNG, basis and full-population correlations", {
  v <- fixture_view(); set.seed(100); old <- .Random.seed
  if(requireNamespace("igraph",quietly=TRUE) && requireNamespace("ggraph",quietly=TRUE)) {
    net <- factor_network(v,direction="both")
    a <- plot_factor_network(net,highlight="F1",gene_labels="all")
    b <- plot_factor_network(net,highlight="F1",gene_labels="all")
    expect_equal(unname(as.matrix(a$data[,c("x","y")])),unname(as.matrix(b$data[,c("x","y")])))
    expect_silent(ggplot2::ggplot_build(a))
    expect_silent(ggplot2::ggplot_build(plot_factor_network(net,layout="stress")))
  }
  md <- data.frame(sample=rownames(v$activity),group=c("a","b","b"))
  plots <- plot_factor_diagnostics(v,md,"group",marker=c(s3=3,s1=1,s2=2),factor="F1",max_samples=2)
  expect_equal(attr(plots$marker,"full_population_correlation"),cor(v$activity[,1],1:3))
  expect_equal(nrow(plots$marker$data),2)
  for(p in plots) expect_silent(ggplot2::ggplot_build(p))
  gate <- factor_gate_alignment(v,cbind(CD1=c(s1=1,s2=2,s3=3)),"F1",positive="CD1",thresholds=c(CD1=1))
  E <- cbind(x=c(s1=1,s2=2,s3=3),y=c(2,1,3))
  expect_silent(ggplot2::ggplot_build(plot_factor_gates(gate,E)))
  expect_silent(ggplot2::ggplot_build(plot_factor_gates(gate,E,display="density")))
  x <- compare_factor_groups(v,md,"group",c("b","a")); y <- compare_factor_groups(v,md,"group",c("a","b"))
  expect_equal(plot_factor_contrasts(x,y)$data$x,-plot_factor_contrasts(x,y)$data$y)
  expect_identical(.Random.seed,old)
})
test_that("default clipped margins match the existing audited helper exactly", {
  v <- fixture_view()
  expect_equal(unname(factor_distinctiveness(v,format="matrix")),unname(.compute_le_effects(v$effects)),ignore_attr=TRUE)
  zero <- .make_representation(v$activity,v$effects*0,v$manifest)
  expect_equal(factor_diagnostics(zero)$factors$active_features,c(0,0))
  net <- factor_network(zero)
  expect_equal(nrow(net$edges),0); expect_equal(nrow(net$nodes),2)
  if(requireNamespace("igraph",quietly=TRUE) && requireNamespace("ggraph",quietly=TRUE)) expect_silent(ggplot2::ggplot_build(plot_factor_network(net)))
  collision <- v$effects; rownames(collision)[1] <- "F1"
  collision <- .make_representation(v$activity,collision,v$manifest)
  net <- factor_network(collision)
  expect_true(all(c("factor:F1","feature:F1") %in% net$nodes$id))
  tie <- .make_representation(cbind(F1=c(s3=1,s2=1,s1=1)),v$effects[,1,drop=FALSE],utils::modifyList(v$manifest,list(native_indices=1)))
  gate <- factor_gate_alignment(tie,cbind(M=c(s1=0,s2=1,s3=0)),"F1",positive="M",thresholds=c(M=0.5))
  expect_equal(gate$activity_ids,"s1")
})
test_that("tied ROC optima choose smallest finite native threshold", {
  skip_if_not_installed("pROC"); v <- fixture_view()
  a <- matrix(c(1,2,3,4),4,1,dimnames=list(paste0("s",1:4),"F1"))
  v <- .make_representation(a,v$effects[,1,drop=FALSE],utils::modifyList(v$manifest,list(native_indices=1)))
  md <- data.frame(sample=rownames(a),group=c("yes","no","yes","no"))
  r <- factor_specificity(v,md,"group",groups="yes",threshold_method="youden")
  native <- pROC::roc(md$group=="yes",a[,1],levels=c(FALSE,TRUE),direction="<",quiet=TRUE)
  best <- pROC::coords(native,"best",best.method="youden",transpose=FALSE)
  expect_gt(nrow(best),1)
  expect_equal(r$threshold_ties,nrow(best))
  expect_equal(r$threshold,min(best$threshold[is.finite(best$threshold)]))
})
